spring.application.name=shift-scheduler-api
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8081}

admin.username=${ADMIN_USER:O6w08.liou:j/X"}
admin.password=${ADMIN_PASS:a/LB8L3b:2L6£8=cvi$ZDe}